### ISSUE TITLE
Can you upload HoudiniEngine daily build to Github, too? 

### ISSUE THREAD

**Issue by eliiik** [sideeffects/HoudiniEngineForUnreal-v2#104]
Currently, in Github, we only can get the stable release of the plugin version. But if we want to test the new feature of the daily build plugin, it will be not so convinient. So is it possible that sync the daily build version of the plugin to Github as well?

**Comment by hyperforce99** [comment]
Today i found out that the h-engine build comes with daily builds (assuming that you install the h-engine from the install window). Look under engine/unreal folder.
My guess is its the latest version.

**Comment by dpernuit** [comment]
Hi,
I can confirm the above, the latest version of the plugin (binaries and source) is available in the daily builds.
This repo is still updated manually, and will only be for the latest stable version.
