### ISSUE TITLE
Severe blocking BUG: In UE4, Buttons on the asset interface are triggered on every recook/reload triggered by the user.

### ISSUE THREAD

**Issue by hyperforce99** [sideeffects/HoudiniEngineForUnreal-v2#108]
Hello side FX, I want to report a bug present in the V2 Houdini Engine for the past half year.

I have previously reported this to Damien by email but it has not yet been addressed and it is a severe / blocking bug for me. 

I'm currently in the process of developing several tools that use a .bgeo cache save/load system.
This works perfectly fine in Houdini and did as well in the v1 Houdini Engine.

However in v2, this bug is causing all the button on the asset interface to trigger on a recook or reload, causing all my ROP-Output drivers to trigger, overwriting my .bgeo cache file (multiple times for every button press) with data, when and not in the way it is supposed to.

Likewise, in other tools (not in the included example) I'm using CSV files to cache data, such as attributes and strings and this is exported using the Labs CSV Exporter. these CSV exporters are also linked to buttons on the interface..

And this too would be affected by unwanted button presses on the interface, potentially destroying my data-sets.

Best case; it removes data from my file that I can recover, worst case, my cache gets corrupted, making it hard to recover anything and I would be forced to load a backup. 

The fact that this bug occurs on a simple recook or reload has completely shut down my ability to use my tools in the v2 UE4 Houdini Engine the way how I was able to in the v1 engine. 
I'm currently only working with them in Houdini directly as a result.

I hope this can be fixed soon as I consider this bug a High Severity bug.
I'm building a masterclass and I would need this bug resolved before I start recording, probably around quarter 2 of this year.

I have included a video on the subject and the files needed to replicate the bug in the Unreal Engine 4.

Sincerely, 
Erwin Heyms

[UE4_H-engine_v2_4.26_buttonPress_Bugreport_files.zip](https://github.com/sideeffects/HoudiniEngineForUnreal-v2/files/5783133/UE4_H-engine_v2_4.26_buttonPress_Bugreport_files.zip)

https://user-images.githubusercontent.com/65279184/103925829-63c74200-5118-11eb-810a-7753a531799f.mp4

**Comment by dpernuit** [comment]
Hi Erwin,

That issue will be fixed in tomorrow's daily build.

When recooking/rebuilding an HDA, we upload ALL the parameter values to Houdini, whether they have changed or not, and force a recook of the HDA (and for rebuild, we also update the HDA definition, and also look for new/modified parameters or inputs).
The issue came from the fact that buttons are triggered when their value is set (no matter what the value is).

Anyway, that's why a normal cook (where we only update changed parameters) didn't cause button presses, while a recook did.

**Comment by hyperforce99** [comment]
Thanks for the quick fix. I will test it tomorrow when the build comes out 😁

**Comment by hyperforce99** [comment]
Was the change submitted/in a released daily build? 
I haven't seen it yet in the changelogs
