### ISSUE TITLE
Feature Request: F_Property support, a.k.a. Per-Instance custom data in v4.25

### ISSUE THREAD

**Issue by hyperforce99** [sideeffects/HoudiniEngineForUnreal-v2#109]
Hello Sesi,

I have a feature request involving the current usage of u-property and the f-property feature added to unreal engine 4.25 last year. 

I'm only familiar with u-properties and how they are used in the Houdini Engine. and have run into its limitations when building my tools.

At the moment we can instance meshes into unreal, but these meshes are always the same, clustered into instance groups. 
Any variation on those meshes, such as material instances can't seem to be set using u-property.

If I understand it correctly, The F_property feature from 4.25 seems to allow this though, setting variables to parts of the instance group without having to split them into different elements for every variation.

This could allow a single instance group to have different variables on its Material instances, materials, etc.
Which in turn would allow me to instruct my meshes to load a whole range of variations on their material instances. 

(color changes at the first thing that comes to mind.)

Is there a chance that this could be supported in the near-distant future ?

**Comment by dpernuit** [comment]
Hi Erwin,

The instancing part of v2 was developed before that feature was added in Unreal, so currently doesn't make use of it.
That is something that we could likely support in the future.

However, v2 supports instancer splitting by attribute values, which could solve your issue:
You can use the "unreal_splitt_attr" string attribute on your instancer, and set its value to the name of another attribute that will be used for splitting, ie:

s@unreal_split_attr = "unreal_material";

will create separate instancer components, one for each value of the "unreal_material" attribute.

Now if you want to split the instancers using multiple attributes, you'd likely need to create an extra attribute (for example, "instancer_id") that would change depending on the combination of parameters you're looking for (ie, color and material etc..)

**Comment by hyperforce99** [comment]
Ok, thanks Damien. 👍 
Would it be theoretically possible or reasonable to output or "bake" the instances into individual instances instead of these clumps of instances ? 

As you can see in the image below when I bake my asset out to static meshes, it clumps together the instances into these static instance containers. Unlike the table on the right which is a manually placed static mesh instance.

I sometimes just want to be able to output my data directly to editable static meshes without having them clumped up or still bound to the Houdini asset.

![objInstance2](https://user-images.githubusercontent.com/65279184/103950831-e4e50000-513d-11eb-89fc-29e57ae01e63.PNG)

**Comment by dpernuit** [comment]
So, if you use the split attribute as mentioned above, you'll get separate instancer components (one per different value of the split attributes).

If you want to split all instances to an individual SMC, then you can use the v1 worklow, by using "unreal_split_instances".
This attribute will split all the instances to Static Mesh Component.

**Comment by hyperforce99** [comment]
Ok thanks, I will have a look at that.

**Comment by dpernuit** [comment]
Just a quick update on that issue, but we will likely soon be adding support for per-instance custom data to the v2 plugin.
(ie, set the num custom float and the custom data array via attributes).

**Comment by hyperforce99** [comment]
Hello Damien, that sounds great :)

I'm currently updating my spawning output nodes so when this will be
available I'll integrate it.

I have a quick question actually,
Is there a way to spawn Decal actors from the Houdini Engine, I suppose I
can then set them certain configurations such as the decal material from
U_properties ?
Since decal actors aren't assets like blueprints or static meshes, i'm not
sure how to spawn them. (I believe I read somewhere it was possible to
spawn lights, so why not Decal Actors).
Otherwise I will spawn a blueprint with a decal actor in it instead.

[image: image.png]

Sincerely,
Erwin Heyms


Op vr 26 feb. 2021 om 20:14 schreef Damien Pernuit <notifications@github.com

**Comment by dpernuit** [comment]
For Decals, IIRC there's two ways you could spawn them via the plugin:
- unreal_instance set to a Material path, with the material set to Decal, this should normally spawn the appropriate DecalActor.
- unreal_instance set to "DecalActor" will spawn DecalActors, and you can try to use uprop attribute to change params.

**Comment by dpernuit** [comment]
Support for per-instance custom data has been added in the latest update.
