### ISSUE TITLE
PDG bake alway make editor crash.

### ISSUE THREAD

**Issue by ghost** [sideeffects/HoudiniEngineForUnreal-v2#114]
i am using latest release houdini engine V2 for Unreal 4.26 and trying pdg here,  when i am clicked pdg bake button unreal editor would crash immediately. i found that BakedOutputContainer.BakedOutputs alway empty when function BakePDGWorkResultObject call function BakeHoudiniOutputsToActors which make editor crash. is it a bug? or is my operate error?

**Comment by kamilhepner** [comment]
The same here, when trying to bake landscape tiles to get world composition working.
![wc_crash_bug](https://user-images.githubusercontent.com/64246548/105778630-98b90d00-5fd1-11eb-8343-a3f38ceec49f.PNG)

PDG network
![wc_crash_pdg](https://user-images.githubusercontent.com/64246548/105778724-ca31d880-5fd1-11eb-8995-561fb7d6c158.PNG)

World composition node
![wc_crash_compNode](https://user-images.githubusercontent.com/64246548/105778765-e170c600-5fd1-11eb-8bfa-6371d184f778.PNG)

Content browser
![wc_crash_contentB](https://user-images.githubusercontent.com/64246548/105778921-38769b00-5fd2-11eb-86cf-b782040a3204.PNG)

World outliner
![wc_crash_worldO](https://user-images.githubusercontent.com/64246548/105778954-42989980-5fd2-11eb-835f-af7f9e76ad38.PNG)

Geometry spreadsheet
![wc_crash_spreadsheet](https://user-images.githubusercontent.com/64246548/105778980-55ab6980-5fd2-11eb-9793-cfc373fc6530.PNG)

All data is there unfortunately it crashes all the time when trying to bake it
![wc_crash_bake](https://user-images.githubusercontent.com/64246548/105779039-707dde00-5fd2-11eb-87eb-feb38b990e1f.PNG)

**Comment by kuimig** [comment]
me too
c:\program files\epic games\ue_4.25\engine\source\runtime\core\public\Containers/Array.h
Assertion failed: (Index >= 0) & (Index < ArrayNum) Array index out of bounds: 0 from an array of size 0
my work folder not in C：

**Comment by dpernuit** [comment]
This issue has been fixed in recent daily builds of Houdini / the plugin.

**Comment by kuimig** [comment]
> This issue has been fixed in recent daily builds of Houdini / the plugin.

thx Damien！
