### ISSUE TITLE
Changing flavor of Houdini launched on "Open scene in Houdini"

### ISSUE THREAD

**Issue by eetumartola** [sideeffects/HoudiniEngineForUnreal-v2#117]
When I click "Open scene in Houdini" from the top menu, it always launches Houdini FX.
I usually use Houdini Core, so when I use that option I end up hogging two licenses.

The plugin settings have an option for selecting a custom location for Houdini, but that only takes in the bin folder.
Either having the ability to select the executable, or even a separate FX/Core/Indie selector would be nice.
(Or checking if a license is already in use, and launching the matching executable)

**Comment by Ryan-DowlingSoka** [comment]
We also would like this. We have a limited number of FX licenses, so would like to require people to consciously launch FX. Most houdini engine things we do only require Core.

**Comment by dpernuit** [comment]
Hi,
Tomorrow's daily build of the plugin will have a new plugin setting that lets you choose the executable to use when opening session sync / hip files. (houdini / fx /core / indie)
