### ISSUE TITLE
Engine does not compile for 18.5-4.25 

### ISSUE THREAD

**Issue by john-holland-ai** [sideeffects/HoudiniEngineForUnreal-v2#118]
Compiling yields the following errors.

/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniRuntimeSettings.cpp:53:2: error: expression result unused [-Werror,-Wunused-value]
        GeneratedWalkableSlopeOverride;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniRuntimeSettings.cpp:54:2: error: expression result unused [-Werror,-Wunused-value]
        GeneratedFoliageDefaultSettings;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniRuntimeSettings.cpp:55:2: error: expression result unused [-Werror,-Wunused-value]
        GeneratedAssetUserData;
        ^~~~~~~~~~~~~~~~~~~~~~

Branch 18.5-4.25
Ubuntu 20.04
UE 4.25
Houdini 18.5.462 (python 3)

**Comment by dpernuit** [comment]
Hi,
We found that issue internally already, the fix will be up soon
