### ISSUE TITLE
No update for the latest Houdini production build 18.5.499?

### ISSUE THREAD

**Issue by eliiik** [sideeffects/HoudiniEngineForUnreal-v2#120]
And I really need the bug fix for daily build:

Houdini 18.5.501 | Version 2:Fixed bugs when using foliage instancers: Previous foliage instances where not always properly cleaned up when directly instancing FoliageTypes, or when switching from foliage instances to "normal" instances.
-- | --

Please consider uploading these features.

**Comment by dpernuit** [comment]
Unfortunately, currently the v2 repo is still manually updated.
I've just updated it to today's production build, H18.5.532.
