### ISSUE TITLE
Incorrect terrain output scale when a terrain has a scale

### ISSUE THREAD

**Issue by ShadeInteractive** [sideeffects/HoudiniEngineForUnreal-v2#121]
### **PROBLEM**
Incorrect terrain output scale when a terrain has a scale on it. 
 
![image](https://user-images.githubusercontent.com/20212204/110122729-446b2f00-7dc0-11eb-9a1d-e5c73948342d.png)

Inside my .hda tool I do not make anything, input and output should be the same.
I don't see the problem in houdini.

### **HIP file**
Scene file from unreal:
[terrain_scale_problem.zip](https://github.com/sideeffects/HoudiniEngineForUnreal-v2/files/6090785/terrain_scale_problem.zip)

### **STEPS TO REPRO:**

- Create a terrain with a scale of 50 50 100
![image](https://user-images.githubusercontent.com/20212204/110121765-16391f80-7dbf-11eb-8bb5-50284ff20730.png)
![image](https://user-images.githubusercontent.com/20212204/110122090-7760f300-7dbf-11eb-9d15-e06818c27572.png)

- Pass the terrain in the tool input
![image](https://user-images.githubusercontent.com/20212204/110123286-04f11280-7dc1-11eb-9ca5-8f137bac60b7.png)

### **QUICK FIX**
Add a transform in houdini with a 0.5 on y value. 

![image](https://user-images.githubusercontent.com/20212204/110123610-66b17c80-7dc1-11eb-9d52-5ee218e785c8.png)

**Comment by eliiik** [comment]
Hi, a pull request has been fix for it a long while ago. https://github.com/sideeffects/HoudiniEngineForUnreal-v2/pull/101
I don't know why SideFX hasn't merged it yet. But you can change several lines of source code and make it work.

**Comment by ShadeInteractive** [comment]
@elikseng Ok thanks I'll do that!!!

**Comment by dpernuit** [comment]
Hi,
Thanks for the fix, it is merged in Houdini 18.5.525.

**Comment by dpernuit** [comment]
The PR has been merged and is in today's update.
