### ISSUE TITLE
Import input as reference will create invalid node name

### ISSUE THREAD

**Issue by eliiik** [sideeffects/HoudiniEngineForUnreal-v2#123]
the node name **input_StaticMesh'/Engine/MapTemplates/SM_Template_Map_Floor.SM_Template_Map_Floor'** is invalid(with **'**) and can't get the geo info.
![企业微信截图_16158614507126](https://user-images.githubusercontent.com/11450267/111247215-8f980400-8642-11eb-882d-3a16a46ebe0f.png)
![企业微信截图_16158614306635](https://user-images.githubusercontent.com/11450267/111247228-91fa5e00-8642-11eb-9332-738268cb9d7d.png)

**Comment by dpernuit** [comment]
Hi,
This will be fixed in tomorrow's daily build. (18.5.557)
