### ISSUE TITLE
Automation: Setting Input Geometry and hitting execute

### ISSUE THREAD

**Issue by Schizo** [sideeffects/HoudiniEngineForUnreal-v2#140]
This topic was already mentioned in #30 I just wanted to start a fresh conversation. Is there a way to set the input geo through Python/BP? 
![image](https://user-images.githubusercontent.com/38006/119207355-ce877300-ba52-11eb-9f5f-3ba54ea8de06.png)

**Comment by dpernuit** [comment]
The plugin now has a Public API that exposes a lot of the plugin's functionalities to c++/BP/Python.

Docs:
https://www.sidefx.com/docs/unreal/_public_a_p_i.html

The example in the docs covers how to set a geo IN.
