### ISSUE TITLE
UE5: Failed to start the houdini session 

### ISSUE THREAD

**Issue by EyezLee** [sideeffects/HoudiniEngineForUnreal-v2#141]
Houdini version: 18.5.351

I unzipped HoudiniEngine file in []https://github.com/sideeffects/HoudiniEngineForUnreal-v2/releases/tag/v2.0.2 and put it in Engine\Plugins\Runtime. But when click Houdini Engine -> Create Session in UE5, it shows Failed to start the houdini session. 

Here is the log from Houdini console:
TPipe ::GetOverlappedResult errored GLE=: errno = 109

**Comment by Bymeoryou** [comment]
Hey @EyezLee , it might be the Houdini engine issue. I have this problem when I start the Houdini session. But when I update my Houdini version from 18.5.532 to 18.5.563, I create the session successfully.

**Comment by EyezLee** [comment]
yes, same here. Once I updated my engine to 563, voila fixed!
