### ISSUE TITLE
HoudiniPublicAPI.h: Bad Reference to HoudiniEngineCommands

### ISSUE THREAD

**Issue by blhook** [sideeffects/HoudiniEngineForUnreal-v2#162]
Hello Houdini Team,

We are having some issues with the HoudiniEngineForUnreal-v2 plugin (Houdini18.5-4.26) deployed with Houdini 18.5.672 (4.26-v2). 

We had previously been utilizing a modified version of the plugin where we manually moved most of the HoudiniEngineRuntime headers to a public folder for consumption for our pre-release testing for an integration with your plugin. With the changes to the HoudiniPublicAPI, we are trying to migrate to the newly exposed public methods, as it is significantly easier to support. 
To this end, we've added a reference to the HoudiniPublicAPI.h in our own plugin code, but are getting a compile error due to `HoudiniEngineCommands.h` unable to be found due to it being located in the Private folder of the HoudiniEngineEditor module. We have manually modified the code in `HoudiniPublicAPI.h` to point to the referenced file directly (`HoudiniEngineEditor/Private/HoudiniEngineCommands.h`) , where this led to some success as the build did work, but we do not want to make edits to 3rd party files for the installation. Our current route to be able to get it to work is manually including the HoidiniEngineEditor's Private folder in our include path which is extremely hacky and brittle.
Due to this all, it looks like there may be an issue on the Houdini side for this reference and it likely needs to be updated from the HoudiniEngineForUnreal-v2 plugin. 

Please let us know if there is any further information you need to debug.

**Comment by blhook** [comment]
The following files and their references seem impacted (are calling Private headers that are non-accessible): 

`HoudiniPublicAPI.h`
 * `HoudiniAssetComponent.h`
 * `HoudiniEngineCommands.h`
 * `HoudiniParameter.h`



`HoudiniPublicAPIAssetWrapper.h`
 * `HoudiniAssetActor.h`
 * `HoudiniAssetComponents.h`
 * `HoudiniEngineCommands.h`
 * `HoudiniParameter.h`
 * `HoudiniPDGAssetLink.h`
 * `IHoudiniAssetStateEvents.h`

**Comment by dpernuit** [comment]
Hi,

Thanks for bringing this up, we had noticed those issues on our end as well, and have a working fix that we're currently testing.
Expect a fix for this during the week (same thing for the missing export that you also reported)

**Comment by blhook** [comment]
This issue appears to have been fixed in the latest release. Appreciate it. 
Closing out.
