### ISSUE TITLE
It seems two source files are missing from the 4.27 branch

### ISSUE THREAD

**Issue by chorakm** [sideeffects/HoudiniEngineForUnreal-v2#169]
We are attempting to compile the plugin for UE-4.27-Chaos, and It seems two files, HoudiniAsset.h, and HoudiniEngineRuntimeCommon.h are missing in the Houdini18.5-4.27 branch. I was able to pull these from the 4.26 branch, and that got me past the UnrealHeaderTool phase of compilation, but not sure if these files are up-to-date for 4.27

**Comment by matsumoto-7** [comment]
I am facing the same problem and my project is using "v2.0 - H18.5.596".
Unfortunately, "v2.0 - H18.5.696" is not available :(

**Comment by dpernuit** [comment]
This issue's been fixed in October
