### ISSUE TITLE
HDA is destroyed regardless of preference when baking

### ISSUE THREAD

**Issue by Bjorn-Darewise** [sideeffects/HoudiniEngineForUnreal-v2#29]
When baking to foliage, the hda is always destroyed which is not respecting the toggle to replace the hda.

edit : Oh wait, it's behaving as expected for the last couple of tries. Never mind.

**Comment by dpernuit** [comment]
This issue is no longer after we changed the way baking works.
Baking now never deletes the HDA, you need to do it manually.
The "replace" bake is now used to replace the previous bake result, but we no longer offer the option to "replace" the HDA with its baked results.
