### ISSUE TITLE
Issue if .hda file has more than one definitions

### ISSUE THREAD

**Issue by kelvincai522** [sideeffects/HoudiniEngineForUnreal-v2#35]
In HE UE V1, if the .hda file has more than one definitions, it opens a dialog to let you choose which one to instantiate in the level.
In V2, it auto chooses the first definition without the V1 dialog.

I would suggest users can choose which definition in the HDA Asset editor window.

I am using the Alpha3 Release binaries for UE4.24

**Comment by dpernuit** [comment]
Hi,
The sub-asset selection dialog was added back in the alpha3.2 update.
