### ISSUE TITLE
Crash if Static Mesh Method is FMesh Description

### ISSUE THREAD

**Issue by kelvincai522** [sideeffects/HoudiniEngineForUnreal-v2#36]
Not sure if it is a bug of HE or UE4 itself.

UE4 crashes if Static Mesh Method is FMesh Description.  Here is the crashlog attached, and HDA used.

[Test64bits.zip](https://github.com/sideeffects/HoudiniEngineForUnreal-v2/files/5076561/Test64bits.zip)

[UE4CC-Windows-F312C1A341E978D785AB50AF217841C9_0001.zip](https://github.com/sideeffects/HoudiniEngineForUnreal-v2/files/5076551/UE4CC-Windows-F312C1A341E978D785AB50AF217841C9_0001.zip)

**Comment by dpernuit** [comment]
Hi,
Thanks for bringing that up, this will be fixed in the next update.

**Comment by dpernuit** [comment]
Hi,
The fix for that crash is now available in the beta1 update.
