### ISSUE TITLE
Houdini Engine v2 - problem with compiling after "make" and "generateProjectFiles.sh" on Linux Mint 20

### ISSUE THREAD

**Issue by djczaps** [sideeffects/HoudiniEngineForUnreal-v2#38]
Hi

I've tried to install new version of the plugin for UE- Alpha3.2. Based on installed Houdini 18.0.532. However it throws a few errors during "make" proces with accesing to some missing staticmeshes.h errors. It compiled but with errors - around 5 errors so far. After generating projectfiles it went 100% fine , no warnings etc. However opening editor throwing errors that HEngine cannot be found or properly installed etc. ( don't have an access to proper logs right now ). I put the new plugins into "old" Plugins/Runtime/HoudiniEngine folder also trying to put a Plugins sections in Unreal Projects and copy the files there with and without making a blank UE compiling ( without HEngine in Runtime section. Any tips how to solve it on Linux ? Or at this stage is only running on Windows ? UE 4.25.1 / Houdini 18.0.532. Old plugin of Houdini Engine v1 based on Houdini 18.0.560 running just fine without any errors. 

greetings

djczaps

**Comment by dpernuit** [comment]
Hi,

As mentioned on the readme, I really do not recommend mixing version 2 files with version 1.
We haven't tested building v2 on Linux (or Mac) yet, so it's likely that the plugin will require a few updates to fix some build errors that are OS specific.

**Comment by mrmowgli** [comment]
I get the same thing.  The specific build issue he mentions is because of a backslash in the include path:
`#include "Engine\StaticMesh.h" ` however fixing that still causes build errors, mostly dealing with shadowing variables.

Attaching build failures: 
[HoudiniUnrealv2_BuildErrors_Ubuntu20.12.txt](https://github.com/sideeffects/HoudiniEngineForUnreal-v2/files/5165311/HoudiniUnrealv2_BuildErrors_Ubuntu20.12.txt)

Note that fixing that backslash allows the build to continue, but hits more errors.

**Comment by dpernuit** [comment]
Hi.

The latest update (beta1) includes a lot fixes for building the plugin on Linux.
Let us know if you still have issue!
(and please send us the errors if you have any)

**Comment by mrmowgli** [comment]
Still getting an error:
```bash
[11/22] Compile Module.HoudiniEngine.4_of_5.cpp
In file included from /home/alewis/dev/UnrealEngine-4.25/Engine/Plugins/Runtime/HoudiniEngine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/HoudiniEngineRuntime/Module.HoudiniEngineRuntime.cpp:6:
/home/mowgli/dev/UnrealEngine-4.25/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniCompatibilityHelpers.cpp:42:10: fatal error: 'HoudiniParameterMultiparm.h' file not found
#include "HoudiniParameterMultiparm.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[12/22] Compile Module.HoudiniEngine.2_of_5.cpp
[13/22] Compile Module.HoudiniEngine.gen.cpp
1 error generated.
```

**Comment by dpernuit** [comment]
Hi,
Damn, I thought I'd fixed this one. P is capital in MultiParm, and linux is case-sensitive

Try:
#include "HoudiniParameterMultiParm.h"

**Comment by mrmowgli** [comment]
That gets me a bit farther, thanks!  However now I get failures  from unused variables.  I'm not seeing a way to turn these off from make, and Unreal build system is a bit convoluted.  I tried `make -Wno-unused-variable` to no avail. Here's the errors:

```bash
[1/5] Compile Module.HoudiniEngineRuntime.cpp
In file included from /home/mowgli/dev/UnrealEngine-4.25/Engine/Plugins/Runtime/HoudiniEngine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/HoudiniEngineRuntime/Module.HoudiniEngineRuntime.cpp:6:
/home/mowgli/dev/UnrealEngine-4.25/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniCompatibilityHelpers.cpp:373:10: error: expression result unused [-Werror,-Wunused-value]
        NewHGPO.AssetName;
        ~~~~~~~ ^~~~~~~~~
/home/mowgli/dev/UnrealEngine-4.25/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniCompatibilityHelpers.cpp:389:10: error: expression result unused [-Werror,-Wunused-value]
        NewHGPO.VolumeName;
        ~~~~~~~ ^~~~~~~~~~
/home/mowgli/dev/UnrealEngine-4.25/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniCompatibilityHelpers.cpp:390:10: error: expression result unused [-Werror,-Wunused-value]
        NewHGPO.VolumeTileIndex;
        ~~~~~~~ ^~~~~~~~~~~~~~~
/home/mowgli/dev/UnrealEngine-4.25/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniCompatibilityHelpers.cpp:394:10: error: expression result unused [-Werror,-Wunused-value]
        NewHGPO.bIsTemplated;
        ~~~~~~~ ^~~~~~~~~~~~
/home/mowgli/dev/UnrealEngine-4.25/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniCompatibilityHelpers.cpp:395:10: error: expression result unused [-Werror,-Wunused-value]
        NewHGPO.bIsInstanced;
        ~~~~~~~ ^~~~~~~~~~~~
/home/mowgli/dev/UnrealEngine-4.25/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniCompatibilityHelpers.cpp:398:10: error: expression result unused [-Werror,-Wunused-value]
        NewHGPO.bHasPartChanged;
        ~~~~~~~ ^~~~~~~~~~~~~~~
/home/mowgli/dev/UnrealEngine-4.25/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniCompatibilityHelpers.cpp:399:10: error: expression result unused [-Werror,-Wunused-value]
        NewHGPO.bHasTransformChanged;
        ~~~~~~~ ^~~~~~~~~~~~~~~~~~~~
/home/mowgli/dev/UnrealEngine-4.25/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniCompatibilityHelpers.cpp:400:10: error: expression result unused [-Werror,-Wunused-value]
        NewHGPO.bHasMaterialsChanged;
        ~~~~~~~ ^~~~~~~~~~~~~~~~~~~~
8 errors generated.
make: *** [Makefile:928: UE4Editor] Error 6
```

**Comment by dpernuit** [comment]
Hi,

Sorry about that, we checked the linux builds BEFORE merging the v1 backward compatibility changes...
Those members are actually unused, and can just be commented out in "HoudiniCompatibilityHelpers.h"

We'll try to address those asap and push a fix on the repo.

**Comment by dpernuit** [comment]
Hi,
Just pushed an update to the repo that should fix those linux build errors.

**Comment by mrmowgli** [comment]
Everything compiles and seems to be working on my side!  Thanks for getting this in!
