### ISSUE TITLE
Any build attempts for 4.25 + (targeting 4.26)

### ISSUE THREAD

**Issue by Schizo** [sideeffects/HoudiniEngineForUnreal-v2#39]
I tried to build it out of the box for 4.26 (Virtual Production) but I got some errors in the convexmesh class. Wondering if someone attempted targeting one of the more unstable branches.

**Comment by dpernuit** [comment]
Have you tried the master branch?
We use 4.26 for development here, and the master branch should build just fine on a recent version of 4.26.
(we last update master on our side a couple of weeks ago)
