### ISSUE TITLE
Transform translate issue

### ISSUE THREAD

**Issue by ArnoChenFx** [sideeffects/HoudiniEngineForUnreal-v2#44]
The swap fuction not need to call, because the scale vector has already swap the Y/Z.

![image](https://user-images.githubusercontent.com/24894259/92697274-b1f05280-f37d-11ea-8f23-a75e3c7f33ee.png)

**Comment by dpernuit** [comment]
Hi,
Thanks for letting us know, this has been fixed in the latest update (beta1),
