### ISSUE TITLE
Pack before merge only pack the first StaticMesh if the input is BluePrint prefab

### ISSUE THREAD

**Issue by kelvincai522** [sideeffects/HoudiniEngineForUnreal-v2#46]
If Pack before merge is turned on, and the Geometry input is a BluePrint prefab.
It only pack the first StaticMesh in the BluePrint prefab, instead of all StaticMesh in one Pack Primtive

**Comment by dpernuit** [comment]
Hi,

This should be fixed in the latest update (beta1), alongside the KeepWorldTransform checkbox which presented the same issue.
The actual expected fix however, is to pack each mesh in the blueprint in a pack prim, not all of them into a single packed prim.

Thanks for reporting this to us!
