### ISSUE TITLE
Crash when input a Blueprint prefab geometry 

### ISSUE THREAD

**Issue by kelvincai522** [sideeffects/HoudiniEngineForUnreal-v2#47]
It might be caused by the blueprint prefab with relatively larger amount of polygons.  However, the combined polygon count is not excessive.

Here is the crashlog.
[UE4CC-Windows-778468BC4AE0EC1B2327E491E88F7FCB_0001.zip](https://github.com/sideeffects/HoudiniEngineForUnreal-v2/files/5242973/UE4CC-Windows-778468BC4AE0EC1B2327E491E88F7FCB_0001.zip)

**Comment by dpernuit** [comment]
Hi,
Thanks for bringing that up!
This should be fixed in the latest update (beta)1.
