### ISSUE TITLE
deleting an hda with pdg link crashes unreal.

### ISSUE THREAD

**Issue by DavidFoss** [sideeffects/HoudiniEngineForUnreal-v2#61]
Deleting an instatiated hda with a topnet inside and previously used pdg link, will crash unreal. I'm currently unable to remove it.

**Comment by DavidFoss** [comment]
Assertion failed: GCCounterValue == 1 [File:D:\work\repos\*******\UnrealEngine\Engine\Source\Runtime\CoreUObject\Private\UObject/GCScopeLock.h] [Line: 100]

UE4Editor_Core
UE4Editor_Core
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_HoudiniEngineRuntime!FTOPWorkResultObject::DestroyResultOutputs() [D:\Plastic\Game\Plugins\HoudiniEngine\Source\HoudiniEngineRuntime\Private\HoudiniPDGAssetLink.cpp:1086]
UE4Editor_HoudiniEngineRuntime!UHoudiniPDGAssetLink::DestroyWorkItemResultData() [D:\Plastic\Game\Plugins\HoudiniEngine\Source\HoudiniEngineRuntime\Private\HoudiniPDGAssetLink.cpp:559]
UE4Editor_HoudiniEngineRuntime!UHoudiniPDGAssetLink::ClearTOPNodeWorkItemResults() [D:\Plastic\Game\Plugins\HoudiniEngine\Source\HoudiniEngineRuntime\Private\HoudiniPDGAssetLink.cpp:459]
UE4Editor_HoudiniEngineRuntime!UHoudiniPDGAssetLink::ClearAllTOPData() [D:\Plastic\Game\Plugins\HoudiniEngine\Source\HoudiniEngineRuntime\Private\HoudiniPDGAssetLink.cpp:438]
UE4Editor_HoudiniEngineRuntime!UHoudiniAssetComponent::OnComponentDestroyed() [D:\Plastic\Game\Plugins\HoudiniEngine\Source\HoudiniEngineRuntime\Private\HoudiniAssetComponent.cpp:1622]
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor_HoudiniEngineRuntime!FHoudiniEngineRuntimeUtils::SafeDeleteObjects() [D:\Plastic\Game\Plugins\HoudiniEngine\Source\HoudiniEngineRuntime\Private\HoudiniEngineRuntimeUtils.cpp:206]
UE4Editor_HoudiniEngineRuntime!FTOPWorkResultObject::DestroyResultOutputs() [D:\Plastic\Game\Plugins\HoudiniEngine\Source\HoudiniEngineRuntime\Private\HoudiniPDGAssetLink.cpp:1088]
UE4Editor_HoudiniEngineRuntime!UHoudiniPDGAssetLink::DestroyWorkItemResultData() [D:\Plastic\Game\Plugins\HoudiniEngine\Source\HoudiniEngineRuntime\Private\HoudiniPDGAssetLink.cpp:559]
UE4Editor_HoudiniEngineRuntime!UHoudiniPDGAssetLink::ClearTOPNodeWorkItemResults() [D:\Plastic\Game\Plugins\HoudiniEngine\Source\HoudiniEngineRuntime\Private\HoudiniPDGAssetLink.cpp:459]
UE4Editor_HoudiniEngineRuntime!UHoudiniPDGAssetLink::ClearAllTOPData() [D:\Plastic\Game\Plugins\HoudiniEngine\Source\HoudiniEngineRuntime\Private\HoudiniPDGAssetLink.cpp:438]
UE4Editor_HoudiniEngineRuntime!UHoudiniAssetComponent::OnComponentDestroyed() [D:\Plastic\Game\Plugins\HoudiniEngine\Source\HoudiniEngineRuntime\Private\HoudiniAssetComponent.cpp:1622]
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor_SceneOutliner
UE4Editor_Slate
UE4Editor_Slate
UE4Editor_Slate
UE4Editor_ApplicationCore
UE4Editor_ApplicationCore
UE4Editor_ApplicationCore
UE4Editor_ApplicationCore
user32
user32
UE4Editor_ApplicationCore
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll

**Comment by dpernuit** [comment]
Hi,
This issue has been fixed a while ago.
