### ISSUE TITLE
Error in unreal_level_path does not fail gracefully

### ISSUE THREAD

**Issue by DionBurgoyne** [sideeffects/HoudiniEngineForUnreal-v2#64]
If the user makes an error when setting the unreal_level_path, houdini engine will crash in unreal when the tool is baked

Fatal error: [File:E:/Jenkins/workspace/ImPcSanity/Engine/Source/Runtime/CoreUObject/Private/Misc/PackageName.cpp] [Line: 512] LongPackageNameToFilename failed to convert '/defaultDirectory/defaultName_x0_y0'. Path does not map to any roots.

UE4Editor_CoreUObject!FPackageName::LongPackageNameToFilename()
UE4Editor_HoudiniEngine!FHoudiniEngineUtils::FindWorldInPackage()
UE4Editor_HoudiniEngine!FHoudiniEngineUtils::FindWorldAndLevelForSpawning()
UE4Editor_HoudiniEngine!FHoudiniLandscapeTranslator::BakeLandscapeObject()
UE4Editor_HoudiniEngine!FHoudiniLandscapeTranslator::BakeLandscape()
UE4Editor_HoudiniEngineEditor!FHoudiniEngineBakeUtils::BakeHoudiniActorToActors()
UE4Editor_HoudiniEngineEditor!FHoudiniEngineBakeUtils::BakeHoudiniActorToActors()

**Comment by dpernuit** [comment]
Hi
This issue should have been fixed in the beta2 update.
