### ISSUE TITLE
Plugin uses display flag instead of output node

### ISSUE THREAD

**Issue by eetumartola** [sideeffects/HoudiniEngineForUnreal-v2#66]
This behavior existed already in v1, and has been tripping me up almost daily.
Houdini itself uses the Output node (if one exists) to determine the output of a network, even if another node is marked as the display node.
The Unreal plugin always uses the display node, even if an Output node exists. This discrepancy in logic often causes me trouble, as it is easy to forget the display node somewhere else than the Output node when working in Houdini.

Surely I'm not the only one? :)

**Comment by yuhe00** [comment]
Yes I noticed this as well. Always forget to set the display flag before saving :P

**Comment by peternicolai** [comment]
Yes. Definitely has tripped me up as well.

**Comment by dpernuit** [comment]
Yes, that's more of a historical limitation, since we couldn't get output nodes via HAPI in the past.

We will likely change this behavior at some point, likely, via a plugin setting/asset option to choose whether to use the display flag/output nodes/both to fetch the results.

**Comment by eetumartola** [comment]
To be honest, in my opinion a setting is not even needed. Just match what Houdini does, why would anyone want a differing behavior? :)

**Comment by eetumartola** [comment]
`Houdini 18.5.738 | By default, the plugin now uses the output nodes found in a HDA instead of the display flag.`

Woohoo! :)
