### ISSUE TITLE
Linux: Build from source compile error

### ISSUE THREAD

**Issue by j0yu** [sideeffects/HoudiniEngineForUnreal-v2#67]
GitHub Ref | 11b3179
---|---
Houdini    | 18.5.351
Unreal Engine | 4.25.4
OS | [CentOS 7.4.1708 (Docker image)][centos7]

### Error

During "make", clang doesn't seem to like "forward references to 'enum' types"

<details><summary>Specifically during the UE4Editor build</summary>

```
bash "/path/to/unreal/Engine/Build/BatchFiles/Linux/Build.sh" UE4Editor Linux Development  
Fixing inconsistent case in filenames.
Setting up Mono
Building UE4Editor...
Using 'git status' to determine working set for adaptive non-unity build (/path/to/unreal).
Creating makefile for UE4Editor (no existing makefile)
Houdini Engine : Found Houdini in /path/to/hfs
Parsing headers for UE4Editor
  Running UnrealHeaderTool UE4Editor "/path/to/unreal/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/UE4Editor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -abslog="/path/to/unreal/Engine/Programs/UnrealBuildTool/Log_UHT.txt"
Reflection code generated for UE4Editor in 23.0737021 seconds
------- Build details --------
Using toolchain located at '/path/to/unreal/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v16_clang-9.0.1-centos7/x86_64-unknown-linux-gnu'.
Using clang (/path/to/unreal/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v16_clang-9.0.1-centos7/x86_64-unknown-linux-gnu/bin/clang++) version '9.0.1' (string), 9 (major), 0 (minor), 1 (patch)
Using bundled libc++ standard C++ library.
Using lld linker
Using llvm-ar : /path/to/unreal/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v16_clang-9.0.1-centos7/x86_64-unknown-linux-gnu/bin/llvm-ar
Using fast way to relink  circularly dependent libraries (no FixDeps).
------------------------------
Building UE4Editor...
Performing 2498 actions (32 in parallel)
```

</details>

```
[1566/2498] Compile Module.SoundCueTemplates.gen.cpp
[1567/2498] Compile Module.HoudiniEngine.5_of_5.cpp
[1568/2498] Compile Module.SteamVRInputDevice.gen.cpp
[1569/2498] Compile Module.SteamVRInputDevice.cpp
[1570/2498] Compile Module.HoudiniEngine.1_of_5.cpp
[1571/2498] Compile Module.HoudiniEngine.2_of_5.cpp
[1572/2498] Compile Module.HoudiniEngine.gen.cpp
[1573/2498] Compile Module.HoudiniEngine.4_of_5.cpp
[1574/2498] Compile Module.Launch.cpp
[1575/2498] Link (lld) libUE4Editor-DatabaseSupport.so
[1576/2498] Compile Module.HoudiniEngine.3_of_5.cpp
[1577/2498] Link (lld) libUE4Editor-ClothingSystemEditor.so
In file included from /path/to/unreal/Engine/Plugins/Runtime/HoudiniEngine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/HoudiniEngine/Module.HoudiniEngine.3_of_5.cpp:2:
In file included from /path/to/unreal/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngine/Private/HoudiniMaterialTranslator.cpp:28:
/path/to/unreal/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngine/Private/HoudiniMaterialTranslator.h:48:6: error: ISO C++ forbids forward references to 'enum' types
enum TextureGroup;
     ^
[1578/2498] Link (lld) libUE4Editor-USDStage.so
```

[Compiler Explorer](https://gcc.godbolt.org/z/nEdTKx) example using clang 9

### Steps to replicate

In short, follow [UnrealEngine Linux] build from source instructions in conjunction with [HoudiniEngineForUnreal-v2 - Building from source] instructions.

1. Download Unreal Engine **tarball** as `/path/to/unreal-source/unreal.tar.gz`
1. Install Houdini 18.5.351 into a directory called `/path/to/hfs`

    i.e. `/path/to/hfs` contains sub-directories:

    - `houdini`
    - `engine`
    - `dsolib`
    - `bin`
    - etc...

1. Start a Docker container exposing `$HFS` environment variable and mounting
   it as read only:

   ```bash
   # You can treat this like a clean, core, CentOS 7.4.1708 install
   docker run --rm -it \
      --env HFS="/path/to/hfs" \
      -v "/path/to/hfs":"/path/to/hfs":ro \
      -v "/path/to/unreal-source/unreal.tar.gz":"/path/to/unreal-source/unreal.tar.gz":ro \
      centos:7.4.1708
   ```

1. Setup with:
    - `unreal` Linux User
    - `make`
    - `pidof` (via `sysvinit-tools`)
    - XDG desktop and user tools

   ```bash
   # Unreal installer prefers not to be run by root, create unreal user
   yum install -y make sysvinit-tools xdg-utils xdg-user-dirs \
      && yum clean all \
      && useradd unreal
   ```

1. Setup install directory for `unreal` user:

    ```bash
    mkdir -vp "/path/to/unreal"
    chmod a+rwx "/path/to/unreal"
    chown unreal:unreal "/path/to/unreal"
    ```
1. Switch to `unreal` user: `su unreal`. 
1. Check `$HFS` environment variable is still set: `echo $HFS`
1. Extract Unreal source code, this will take a while

    ```bash
    tar -xz \
      --strip-components=1 \
      -C "/path/to/unreal" \
      -f "/path/to/unreal-source/unreal.tar.gz"
    ```

1. Download and extract Houdini Engine

    ```bash
    mkdir -vp "/path/to/unreal/Engine/Plugins/Runtime/HoudiniEngine"
    curl -L https://github.com/sideeffects/HoudiniEngineForUnreal-v2/archive/11b3179.tar.gz \
    | tar --strip-components=1 -xz -C "/path/to/unreal/Engine/Plugins/Runtime/HoudiniEngine"
    ```

1. Follow the [UnrealEngine Linux] instructions

    ```bash
    cd "/path/to/unreal"
    ./Setup.sh  # Takes a while
    ./GenerateProjectFiles.sh   # also takes a while

    # This takes the longest, SHOULD error during UE4Editor
    make  # DO NOT: use -j, simultaneously compilation will CRASH library linker
    ```

[centos7]: https://hub.docker.com/layers/centos/library/centos/7.4.1708/images/sha256-9f266d35e02cc56fe11a70ecdbe918ea091d828736521c91dda4cc0c287856a9?context=explore
[HoudiniEngineForUnreal-v2 - Building from source]: https://github.com/sideeffects/HoudiniEngineForUnreal-v2/blob/11b3179/README.md#building-from-source
[UnrealEngine Linux]: https://docs.unrealengine.com/en-US/Platforms/Linux/BeginnerLinuxDeveloper/SettingUpAnUnrealWorkflow/#3-buildingue4onlinux

**Comment by j0yu** [comment]
So, it seems like this hack to `Source/HoudiniEngine/Private/HoudiniMaterialTranslator.h` makes it compile again:

1. Add `#include "Engine/TextureDefines.h"`
2. Remove `enum TextureGroup`

Something along the lines of:

```bash
sed --in-place=.backup '/enum TextureGroup/d; /include "UObject/ a #include "Engine/TextureDefines.h"' \
    Source/HoudiniEngine/Private/HoudiniMaterialTranslator.h
```

Logic being that the `TextureGroup` enum is defined in Unreal's `TextureDefines.h`, but might be a better way to do this since I haven't touched modern C++

**Comment by dpernuit** [comment]
Hi,

Thanks for the detailed report, we actually had already fixed that issue on our side.
You "Hack" is not an hack, but the proper solution to that build issue.
We didn't get the build error on windows, since clang is a little more picky than VS.

The fix will be in the next update.
