### ISSUE TITLE
If voxel padding is used in tilesplit, nothing would appear in unreal from an HDA

### ISSUE THREAD

**Issue by DionBurgoyne** [sideeffects/HoudiniEngineForUnreal-v2#73]
If the user utilizes tilesplit and voxel padding is set to 1 the tiles will not appear in Unreal from the tool, sometimes only one tile shows up, sometimes none.

**Comment by dpernuit** [comment]
Hi,
As I mentioned in your other issue, this has likely been fixed in 18.5.400.
