### ISSUE TITLE
Engine skips a regular pattern of tiles when tile split is used to divide some landscapes

### ISSUE THREAD

**Issue by DionBurgoyne** [sideeffects/HoudiniEngineForUnreal-v2#76]
In this case I'm using a 4033 heightfield split into 10x10, On import into Unreal, engine loses every third tile to show a regular pattern in the missing landscape. I successfully made it work on different levels and different heightfield sizes, but some combinations generate this pattern. When the scene is loaded back into houdini all of the tiles are present

**Comment by DionBurgoyne** [comment]
![image](https://user-images.githubusercontent.com/43759452/99479762-a84e1280-290b-11eb-9067-22e0390f4fad.png)

**Comment by dpernuit** [comment]
Hi Dion,
I suspect that this issue has been fixed in today's daily build (18.5.400).
I fixed an issue that caused missing landscape tiles when their size differed.

**Comment by DionBurgoyne** [comment]
Fixed!
