### ISSUE TITLE
Optional "Cook on curve changed" has no effect when disable

### ISSUE THREAD

**Issue by wakare** [sideeffects/HoudiniEngineForUnreal-v2#81]
bool
FHoudiniSplineComponentVisualizer::IsCookOnCurveChanged(UHoudiniSplineComponent * InHoudiniSplineComponent) 
{

	if (!InHoudiniSplineComponent)
		return true;

	UHoudiniInputObject * InputObject = Cast<UHoudiniInputObject>(EditedHoudiniSplineComponent->GetOuter());
	if (!InputObject)
		return true;

	UHoudiniInput * Input = Cast<UHoudiniInput>(InputObject->GetOuter());

	if (!Input)
		return true;

	return Input->GetCookOnCurveChange();
};

In this implement, always exit in line "UHoudiniInput * Input = Cast<UHoudiniInput>(InputObject->GetOuter());"
which means IsCookOnCurveChanged() never return false.

**Comment by dpernuit** [comment]
Hi,
Thanks for mentioning this.
We've already fixed that issue a few weeks ago, the fix is already in the dailies.
