### ISSUE TITLE
Rebuild does not bring in altered parameters into the interface

### ISSUE THREAD

**Issue by DionBurgoyne** [sideeffects/HoudiniEngineForUnreal-v2#84]
If the user changes the parameters, add or remove, on an HDA, the unreal parameter interface will not update even on a rebuild, the user has to reset the parameters (which could be many settings on tools that are in production) or delete the tool and re-add it to update.

**Comment by dpernuit** [comment]
Hi,

Rebuild should update with the newly added parameters on the HDA, that is something that I do almost every day... 
How is your project setup? do you import the hdas in the unreal project so they can be source controlled? 
Do you happen to also have a copy of that hda in the default hda folder (documents/houdini18.5/otls) ?

Do you see any mention about "loading the hda from memory" in the logs?

What version of UE and H are you using?
