### ISSUE TITLE
Crash when translating ue4-mesh with multiple materials and different textureparameters to houdini

### ISSUE THREAD

**Issue by WWWiemer** [sideeffects/HoudiniEngineForUnreal-v2#87]
Steps to reproduce:

1. Create a HDA with any object path input
2. Prepare a mesh with two material-slots and two materials, that each have a texture-parameter, that is named differently (e.g. texture1 and texture2)
3. In UE4 use the HDA in a scene and assign the prepared mesh as a geometry-input
4. try recooking
 
Tested with PluginV2
    Houdini Version: 18.0.597
    Houdini Engine Version: 3.4.0
    Unreal Version: 4.24.0

and
    Houdini Version: 18.5.408
    Houdini Engine Version: 3.5.1
    Unreal Version: 4.24.0

Provided plugin and HDA for easier reproduction.
[CrashTest.zip](https://github.com/sideeffects/HoudiniEngineForUnreal-v2/files/5629426/CrashTest.zip)

**Comment by punaparta** [comment]
We had the same crash recently, but i never figured it is the texture-parameter part. Good that someone figured out whats the reason.. I noticed it happens on objects with multiple materials, but not always.. I was hunting the cause of this for ages :D

**Comment by eliiik** [comment]
I just comment out the crash part of the source code, and it doesn't crash again :)
btw, the crash point
![image](https://user-images.githubusercontent.com/11450267/103207003-30c2c880-4938-11eb-81c3-16a981b14cf2.png)

**Comment by dpernuit** [comment]
Hi,
Yes, the material parameters marshalling caused a few issues, and has currently been disabled.
