### ISSUE TITLE
When Closing an Editable Curve, the Houdini Session is Lost

### ISSUE THREAD

**Issue by klamme** [sideeffects/HoudiniEngineForUnreal-v2#89]
I have an HDA that has an Editable curve in it to drive a sweep node.  I also promoted the closed parm to the HDA, so I can choose between closed or not closed.  But when I toggle this on in Hengine, the HEngine loses its session and bails.  If I uncheck the close parm, restart the Session and move a point, the geometry comes back and the session stays intact. 

![hengine_v2_curve_issue_002](https://user-images.githubusercontent.com/10983694/100913025-10f9cb00-3486-11eb-88f2-827eeed870cd.gif)

Thanks!  New HEngine is very slick!

**Comment by peterprickarz** [comment]
Can confirm, I had the same issue. While waiting until it's fixed,

"int primpts[] = primpoints(0,0);
append(primpts,0);

addprim(0,"polyline",primpts);
removeprim(0,0,0);"

in a prim wrangle closes the curve as well.

**Comment by dpernuit** [comment]
Hi,
This issue will be fixed in tomorrow's daily build.
