### ISSUE TITLE
When using Foliage Types to instance they do not clean up after each cook.  Leaving old instances. 

### ISSUE THREAD

**Issue by klamme** [sideeffects/HoudiniEngineForUnreal-v2#90]
I was playing with the Data Tables and Foliage Types, and everything works except when I go to re-cook the HDA.  Anything that is a Foliage Type doesn't get cleaned up leaving the old instances in their place...

![hengine_v2_foliagetype_issue_001](https://user-images.githubusercontent.com/10983694/100917689-53260b00-348c-11eb-9f03-d5547450155d.gif)

**Comment by aiiven** [comment]
It happened to me as well, I had to delete them manually in the world.

**Comment by eliiik** [comment]
I have the same problem as well, it's annoying.

**Comment by dpernuit** [comment]
Hi,
This will be fixed in tomorrow's daily build of the plugin.
There was indeed a few cases where previous foliage instances were not properly cleaned up, mainly when directly using foliage types or when switching from foliage instancers to "regular" instancers.
