### ISSUE TITLE
Building errors for 4.26

### ISSUE THREAD

**Issue by avdept** [sideeffects/HoudiniEngineForUnreal-v2#93]
So, I've pulled latest master-18.5 and tried to build it with UE 4.26. While building getting missing dependency issue which looks like

`  unresolved external symbol "__declspec(dllimport) private: static class UClass * __cdecl UPhysicalMaterial::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@UPhysicalMaterial@@CAPEAVUClass@@XZ)`

Did I miss anything or HE for 4.26 not ready yet?

**Comment by saberuster** [comment]
@avdept add "PhysicalCore" module in HoudiniEngine.Build.cs can resovle it.

**Comment by dpernuit** [comment]
I just committed the source code for the 4.26 v2 plugin.
The H18.5 master branch is based an older version of the ue-master branch (4.27).
