### ISSUE TITLE
Houdini18.5-4.25 is not in a buildable state

### ISSUE THREAD

**Issue by boarnoah** [sideeffects/HoudiniEngineForUnreal-v2#95]
Tested with a few configurations (UE at 4.25.4, Houdini at 18.5.408):

Branch "Houdini18.5-4.25" (git tag "v0.14-Beta2"):
Failed build (there are syntax errors in this version when looking at it's source):

```
<project>/Plugins/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniInputObject.cpp(230): error C2511: 'UObject *UHoudiniInputObject::GetObject(void)': overloaded member function not found in 'UHoudiniInputObject'
<project>/Plugins/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniInputObject.cpp(289): error C2511: 'UHoudiniSplineComponent *UHoudiniInputHoudiniSplineComponent::GetCurveComponent(void)': overloaded member function not found in 'UHoudiniInputHoudiniSplineComponent'
<project>/Plugins/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniInputObject.cpp(290): error C2065: 'MyHoudiniSplineComponent': undeclared identifier
<project>/Plugins/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniInputObject.cpp(475): error C2509: 'CopyStateFrom': member function not declared in 'UHoudiniInputHoudiniSplineComponent'
<project>/Plugins/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniInputObject.cpp(1040): error C2065: 'MyHoudiniSplineComponent': undeclared identifier
<project>/Plugins/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniInputObject.cpp(1042): error C2065: 'MyHoudiniSplineComponent': undeclared identifier
<project>/Plugins/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniInputObject.cpp(1042): error C2065: 'MyHoudiniSplineComponent': undeclared identifier
<project>/Plugins/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniInputObject.cpp(1051): error C2065: 'MyHoudiniSplineComponent': undeclared identifier
<project>/Plugins/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniInputObject.cpp(1052): error C2065: 'MyHoudiniSplineComponent': undeclared identifier
```

As a sanity check, I checked out the commit just prior to the beta 2 merge (4ce34dfabf35e3f4f4733ba94b65d6b66db6aad0) and was able to build succesfully as well as launch a Houdini Engine session (with the older Houdini "18.5.351" version).

**Comment by john-holland-ai** [comment]
Manually fixing those errors will get me past the compile state, but I get linker errors

`[1/4] Link (lld) libUE4Editor-HoudiniEngineRuntime.so
ld.lld: error: undefined symbol: UHoudiniInputHoudiniSplineComponent::GetObject() const
>>> referenced by Module.HoudiniEngineRuntime.cpp
>>>               /media/jholland/UbuntuData/ThirdParty/Epic/UnrealEngine/Engine/Plugins/Runtime/HoudiniEngine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/HoudiniEngineRuntime/Module.HoudiniEngineRuntime.cpp.o:(vtable for UHoudiniInputHoudiniSplineComponent)

ld.lld: error: undefined symbol: UHoudiniInputHoudiniSplineComponent::HasChanged() const
>>> referenced by Module.HoudiniEngineRuntime.cpp
>>>               /media/jholland/UbuntuData/ThirdParty/Epic/UnrealEngine/Engine/Plugins/Runtime/HoudiniEngine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/HoudiniEngineRuntime/Module.HoudiniEngineRuntime.cpp.o:(vtable for UHoudiniInputHoudiniSplineComponent)

ld.lld: error: undefined symbol: UHoudiniInputHoudiniSplineComponent::NeedsToTriggerUpdate() const
>>> referenced by Module.HoudiniEngineRuntime.cpp
>>>               /media/jholland/UbuntuData/ThirdParty/Epic/UnrealEngine/Engine/Plugins/Runtime/HoudiniEngine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/HoudiniEngineRuntime/Module.HoudiniEngineRuntime.cpp.o:(vtable for UHoudiniInputHoudiniSplineComponent)

ld.lld: error: undefined symbol: UHoudiniInputHoudiniSplineComponent::MarkChanged(bool const&)
>>> referenced by Module.HoudiniEngineRuntime.cpp
>>>               /media/jholland/UbuntuData/ThirdParty/Epic/UnrealEngine/Engine/Plugins/Runtime/HoudiniEngine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/HoudiniEngineRuntime/Module.HoudiniEngineRuntime.cpp.o:(vtable for UHoudiniInputHoudiniSplineComponent)

ld.lld: error: undefined symbol: UHoudiniInputHoudiniSplineComponent::SetNeedsToTriggerUpdate(bool const&)
>>> referenced by Module.HoudiniEngineRuntime.cpp
>>>               /media/jholland/UbuntuData/ThirdParty/Epic/UnrealEngine/Engine/Plugins/Runtime/HoudiniEngine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/HoudiniEngineRuntime/Module.HoudiniEngineRuntime.cpp.o:(vtable for UHoudiniInputHoudiniSplineComponent)

ld.lld: error: undefined symbol: UHoudiniInputDataTable::UHoudiniInputDataTable(FObjectInitializer const&)
>>> referenced by HoudiniInputObject.h:800 (../Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniInputObject.h:800)
>>>               /media/jholland/UbuntuData/ThirdParty/Epic/UnrealEngine/Engine/Plugins/Runtime/HoudiniEngine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/HoudiniEngineRuntime/Module.HoudiniEngineRuntime.gen.2_of_4.cpp.o:(void InternalConstructor<UHoudiniInputDataTable>(FObjectInitializer const&))
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:928: UE4Editor] Error 6
`

**Comment by dpernuit** [comment]
Hi,
Sorry about that, it seems like some changes were lost in translation when I pushed the 18.5-4.25 code update here on Git.
I just pushed an update that should fix this issue.
