### ISSUE TITLE
Can't click on parms "through" cooking notifications

### ISSUE THREAD

**Issue by peterprickarz** [sideeffects/HoudiniEngineForUnreal-v2#97]
I really like the new notifications and that you get a lot more information, but they take up quite a large amount of space in the area where you usually have the parameter interface. If you have things like a button that the user might need to press multiple times in a row(imagine rotating something by 90 degrees with a button click), the notifications often get in front of the button, and the click isn't registered anymore.

**Comment by dpernuit** [comment]
Hi,
This should be fixed in the latest update, we've tried our best to tame those notifications, and prevent them from piling up too much.
