### ISSUE TITLE
Import hda which contains closed editable output spline component causes HEV2 crash

### ISSUE THREAD

**Issue by wakare** [sideeffects/HoudiniEngineForUnreal-v2#99]
This is my test hda.
[ip_area_generator.zip](https://github.com/sideeffects/HoudiniEngineForUnreal-v2/files/5676831/ip_area_generator.zip)

**Comment by dpernuit** [comment]
Hi,
Seems like your file wasnt uploaded properly... 
Could you send it again?

**Comment by wakare** [comment]
[ip_area_generator.zip](https://github.com/sideeffects/HoudiniEngineForUnreal-v2/files/5682539/ip_area_generator.zip)
Sorry,this time I ensure this file can be download

**Comment by dpernuit** [comment]
Hi,
This issue will be fixed in tomorrow's daily build.
